name: Build and Deploy with Yarn

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn' # Кэшируем зависимости yarn для ускорения

      - name: Install Dependencies with Yarn
        run: yarn install --frozen-lockfile # Используем yarn

      - name: Build with Yarn
        run: yarn build # Используем yarn

      - name: Debug - Show build result
        run: ls -la dist/ || echo "Dist folder not found!"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4